

export const  GET_CRYPTO_DATA_SUCCESS="GET_CRYPTO_DATA_SUCCES";
export const  GET_CRYPTO_DATA_REQUEST="GET_CRYPTO_DATA_REQUEST";
export const  GET_CRYPTO_DATA_FAILURE="GET_CRYPTO_DATA_FAILURE";

export const GET_SHARES_DATA_SUCCESS = "GET_SHARES_DATA_SUCCES";
export const GET_SHARES_DATA_REQUEST = "GET_SHARES_DATA_REQUEST";
export const GET_SHARES_DATA_FAILURE = "GET_SHARES_DATA_FAILURE";